# Generated by Django 3.2.4 on 2021-08-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Directorate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time_end',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_start',
            field=models.TextField(max_length=50),
        ),
    ]
