# Generated by Django 3.2.4 on 2021-08-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.CharField(max_length=200)),
                ('currently_working', models.CharField(max_length=200)),
                ('previously_working', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('college', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=50)),
                ('graduation_year', models.IntegerField()),
                ('number', models.IntegerField()),
            ],
        ),
    ]
